title:    Kathleen McArthur
logo: /Kathleen McArthur/Source Folders/Data/Photos/Kathlene_Painting.jpg
description:     Project developed by Reza Nejad
#show_downloads: true
theme: jekyll-theme-Minimal
